# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Frosty Bay
email: contato@frostybay.com
description: > # this means to ignore newlines until "baseurl:"
  Frosty Bay is an indie game development studio based in Itapema, Brazil and
  this is our website. This is where we put some articles about interesting stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://frostybay.com" # the base hostname & protocol for your site
# twitter_username: frostybay
github_username:  frostybay
permalink: /:categories/:title.html

# Build settings
markdown: kramdown
